services:
  - type: web
    name: edit-shop-bot
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8755950259:AAHpBRy-4GPf1Ulz63Bt_0a9O-g5UmQ4Ym0
      - key: PORT
        value: 8080
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
